version: '3.8'

networks:
  app-tier:
    driver: bridge


services:
  mariadb:
    build:
      context: ./sql
      dockerfile: Dockerfile
    networks:
      - app-tier
  sqlpad:
    # To use Dockerfile at root of this project, use build instead of image
    # build: ../../
    image: sqlpad/sqlpad:latest
    hostname: 'sqlpad'
    depends_on:
      - 'mariadb'
    ports:
      - '3000:3000'
    networks:
      - app-tier
    environment:
      SQLPAD_ADMIN: 'admin@sqlpad.com'
      SQLPAD_ADMIN_PASSWORD: 'admin'
      SQLPAD_APP_LOG_LEVEL: debug
      SQLPAD_WEB_LOG_LEVEL: warn
      # This adds a pre-configured connection to point to the database
      # used as the backend for SQLPad itself
      SQLPAD_CONNECTIONS__mariad__name: 'Tranzactii bancare'
      SQLPAD_CONNECTIONS__mariad__driver: mysql
      SQLPAD_CONNECTIONS__mariad__host: mariadb
      SQLPAD_CONNECTIONS__mariad__port: 3306
      SQLPAD_CONNECTIONS__mariad__database: tranzactidb
      SQLPAD_CONNECTIONS__mariad__username: root
      SQLPAD_CONNECTIONS__mariad__password: password
      # SQLPAD_CONNECTIONS__mariad__multiStatementTransactionEnabled: 'true'
      # SQLPAD_CONNECTIONS__mariad__idleTimeoutSeconds: 86400
  web_app:
    build:
      context: ./web_app
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    expose:
      - '5000'
    networks:
      - app-tier
